name: Node CI

on: [push, pull_request]

jobs:
  backend_build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: cd common && npm ci && npm run build
    - run: cd backend && npm ci
    - run: cd backend && npm run build

  frontend_build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd common && npm ci && npm run build
      - run: cd frontend && npm ci
      - run: cd frontend && npm run build
